// Generated by CoffeeScript 1.7.1
(function() {
  var data, needle, options, url;

  needle = require("needle");

  options = {};

  url = "www.w3schools.com/webservices/tempconvert.asmx?op=CelsiusToFahrenheit";

  data = "<?xml version=\"1.0\" encoding=\"utf-8\"?> <soap12:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:soap12=\"http://www.w3.org/2003/05/soap-envelope\"> <soap12:Body> <CelsiusToFahrenheit xmlns=\"http://www.w3schools.com/webservices/\"> <Celsius>10</Celsius> </CelsiusToFahrenheit> </soap12:Body> </soap12:Envelope>";

  options = {
    headers: {
      'Content-Type': 'application/soap+xml'
    }
  };

  needle.post(url, data, options, function(err, resp, body) {
    return console.log(body.toString());
  });

}).call(this);
