This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./newthesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file newthesis.acn....done (162 entries accepted, 0 rejected).
Sorting entries....done (1347 comparisons).
Generating output file newthesis.acr....done (88 lines written, 0 warnings).
Output written in newthesis.acr.
Transcript written in newthesis.alg.
