This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./newthesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file newthesis.acn....done (223 entries accepted, 0 rejected).
Sorting entries.....done (2025 comparisons).
Generating output file newthesis.acr....done (119 lines written, 0 warnings).
Output written in newthesis.acr.
Transcript written in newthesis.alg.
